### PR TITLE
fix(grpc): handle NotImplementedError from add_done_callback in aio client

### LINKED ISSUE #3915: opentelemetry-instrumentation-grpc: Client unary call throws NotImplementedError
### Describe your environment

OS: Windows 10
Python version: 3.13.1
Package version: opentelemetry-instrumentation-grpc 0.59b0

### What happened?

Unlike the sync version, `add_done_callback` is not implemented for grpc aio client unary-unary call. 
``` python
File "C:\***\.venv\Lib\site-packages\opentelemetry\instrumentation\grpc\_aio_client.py", line 117, in _wrap_    call.add_done_callback(
    ~~~~~~~~~~~~~~~~~~~~~~^
        _unary_done_callback(
        ^^^^^^^^^^^^^^^^^^^^^
            span, code, details, self._call_response_hook
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        )
        ^
    )
    ^
  File "C:\***\.venv\Lib\site-packages\grpc\aio\_interceptor.py", line 1063, in add_done_callback                                                                                                                           allback
    raise NotImplementedError()
NotImplementedError
```

### Steps to Reproduce

1. Install opentelemetry-instrumentation-grpc
2. Globally instrument in code with
``` python
from opentelemetry.instrumentation.grpc import GrpcAioInstrumentorClient, GrpcInstrumentorClient
GrpcAioInstrumentorClient().instrument()
GrpcInstrumentorClient().instrument()
```
3. Use grpc client and make a client call through on any method (I used `grpc.aio.insecure_channel`)

### Expected Result

No opentelemetry instrumentation exception during client call

### Actual Result

Exception from opentelemetry instrumentation 

### Additional context

Source:
https://github.com/grpc/grpc/blob/f0ea80fa6adecc10df9d852897493bd4ca393a15/src/python/grpcio/grpc/aio/_interceptor.py#L1044

For client unary call, I think it should be okay to directly call, I believe call can either be an awaitable Call object or the actual response, something like:
``` python
if isinstance(call, grpc.aio.UnaryUnaryCall):
    response = await call
else:
    response = call
self._call_response_hook(...)
...
return response
```
Perhaps also add a catch-call try block to skip trace so that users don't break if there is an issue between instrumentation and grpc library

### Would you like to implement a fix?

None

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by alliasgher**
## Description

When a user-provided `grpc.aio` interceptor awaits the call object, the resulting type may not implement `add_done_callback` — calling it raises `NotImplementedError`. Catch the exception and invoke the callback immediately with the already-available `code` and `details`, which matches the synchronous interceptor path and keeps span finalisation working.

Fixes #3915

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Added `test_done_callback_not_implemented` in `test_aio_client_interceptor.py` which replaces `add_done_callback` with a function that raises `NotImplementedError` and asserts the span still completes with the correct status.

## Checklist

- [x] Changelog entry added under `Unreleased / Fixed`, linking to PR #4429

### CODE REVIEW

**Comment by xrmx** [comment]
This is missing a test for checking this is working fine now and conflict handling in the CHANGELOG

**Comment by alliasgher** [comment]
I think the comment about #47040 was meant for a different PR (it's a collector-contrib PR fixing the azurefunctions config round-trip, unrelated to this grpc aio fix). Happy to proceed here if that's correct.

**Comment by alliasgher** [comment]
Added a regression test in 2555c4d7 that patches `grpc.aio.UnaryUnaryCall.add_done_callback` to raise `NotImplementedError` and verifies the span is still correctly finished with all expected attributes.

File: CHANGELOG.md [hunk 1]
```diff
@@ -11,6 +11,11 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 ## Unreleased
 
+### Fixed
+
+- `opentelemetry-instrumentation-grpc`: Fix `NotImplementedError` when `grpc.aio` call object does not implement `add_done_callback` (e.g. when a user interceptor awaits the call)
+  ([#3915](https://github.com/open-telemetry/opentelemetry-python-contrib/issues/3915))
```
Comment (MikeGoldsmith) [inline CHANGELOG.md]: Changelog entries should be linked to the PR, not associated issues.

```suggestion
  ([#3915](https://github.com/open-telemetry/opentelemetry-python-contrib/issues/4429))
```

**Review by MikeGoldsmith — CHANGES_REQUESTED** [review]
Change looks good. I've left a suggestion for updating the changelog entry.

Also, please can you update the PR description to use the template we have for consistency.

File: CHANGELOG.md (hunk 1 above)
Comment (alliasgher) [reply CHANGELOG.md]: Done — CHANGELOG now links to PR #4429. Updated PR description to use the standard template.

**Review by MikeGoldsmith — APPROVED** [review]
Looks good - thanks @alliasgher.

**Comment by alliasgher** [comment]
> Looks good - thanks @alliasgher.

@MikeGoldsmith approved but still marked stale

**Comment by emdneto** [comment]
Thanks for the PR!

Just a heads-up: we no longer update `CHANGELOG.md` directly. The changelog is now generated from changelog fragments using Towncrier.

Please add the appropriate changelog fragment for this change instead of editing `CHANGELOG.md` manually. You can find the instructions and expected format in [CONTRIBUTING.md](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/CONTRIBUTING.md#changelog).

**Comment by alliasgher** [comment]
Thanks @emdneto. Rebased onto main and moved the changelog entry to a towncrier fragment (.changelog/4429.fixed) in e3cec30e. Note this PR is still active; #4672 appears to be a copy of this fix.

**Comment by xrmx** [comment]
@alliasgher Please run `tox -e precommit`

**Comment by alliasgher** [comment]
Ran the ruff-format precommit hook and pushed the reformatting in 9b127ab.

**Review by tammy-baylis-swi — APPROVED** [review]

**Review by herin049 — APPROVED** [review]
