### ISSUE TITLE
FastAPI instrumentation: AttributeError on Match.PARTIAL when route has no `.path` attribute (_IncludedRouter from include_router())

### ISSUE THREAD

**Issue by virgotopia** [open-telemetry/opentelemetry-python-contrib#4732]
### Describe your environment

- opentelemetry-instrumentation-fastapi: 0.62b1, 0.63b1 (regression from 0.59b0)
- opentelemetry-instrumentation-asgi: 0.62b1, 0.63b1
- FastAPI: 0.136.1
- Starlette: 1.0.0
- Python: 3.13
- Uvicorn: latest

### What happened?

Every HTTP OPTIONS preflight request (CORS browser preflight) results in a 500 Internal Server Error. The crash occurs inside _get_route_details() in opentelemetry/instrumentation/fastapi/__init__.py when iterating over the app's routes.

The FULL match branch (line ~489) has a try/except AttributeError guard for routes without a .path attribute. The PARTIAL match branch (line ~495) does not — it accesses .path directly and crashes when the matched object is a Starlette _IncludedRouter, which is produced internally by app.include_router() and has no .path attribute.

Because the crash happens inside the OTEL ASGI middleware — which is positioned outside CORSMiddleware in the stack — the 500 response is emitted before CORS headers are added. Browsers therefore report this as a CORS failure, masking the real error.

Regular GET/POST requests are unaffected: they match a concrete leaf Route object at Match.FULL, which takes the guarded path.

### Steps to Reproduce

# main.py
from fastapi import FastAPI, APIRouter
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor

app = FastAPI()
router = APIRouter(prefix="/api/v1")

@router.get("/items/")
def list_items():
    return []

app.include_router(router)
FastAPIInstrumentor().instrument_app(app)

uvicorn main:app --port 8000
curl -X OPTIONS http://localhost:8000/api/v1/items/ \
  -H "Origin: http://localhost:3000" \
  -H "Access-Control-Request-Method: GET"
Expected: 200 (or 204) with CORS headers, or at minimum no exception.

Actual: 500 Internal Server Error with the following traceback:

AttributeError: '_IncludedRouter' object has no attribute 'path'

  File ".../opentelemetry/instrumentation/fastapi/__init__.py", line 495, in _get_route_details
    route = starlette_route.path
  File ".../opentelemetry/instrumentation/fastapi/__init__.py", line 508, in _get_default_span_details
    span_name, additional_attributes = self.default_span_details(scope)
  File ".../opentelemetry/instrumentation/asgi/__init__.py", line 750, in __call__
    await self.app(scope, receive, _send)
  File ".../starlette/middleware/errors.py", line 186, in __call__
    raise exc

In _get_route_details(), starlette_route.matches() returns Match.PARTIAL for _IncludedRouter objects before falling through to the concrete leaf route. _IncludedRouter has no .path attribute.

# FULL match — guarded correctly:
if match == Match.FULL:
    try:
        route = starlette_route.path     # ← protected
    except AttributeError:
        route = scope.get("path")
    break

# PARTIAL match — NOT guarded (the bug):
if match == Match.PARTIAL:
    route = starlette_route.path         # ← AttributeError here

### Expected Result

The PARTIAL match branch should have the same try/except AttributeError guard as the FULL match branch:

if match == Match.PARTIAL:
    try:
        route = starlette_route.path
    except AttributeError:
        route = scope.get("path")

### Actual Result

AttributeError: '_IncludedRouter' object has no attribute 'path' — unhandled exception propagates as HTTP 500.

### Additional context

Introduced in 0.62b1. Works correctly in 0.59b0 (the PARTIAL branch was likely never hit in older Starlette/FastAPI combinations, or routing internals changed).
Still reproducible in 0.63b1.
The fix is a one-liner: wrap line ~495 with the same try/except AttributeError already present at line ~489.
The OPTIONS method is the most common trigger because Starlette's routing matches _IncludedRouter as PARTIAL before reaching the leaf route — regular methods tend to reach FULL on the first matching object.

### Would you like to implement a fix?

Yes

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

**Comment by xrmx** [comment]
Isn't this a dup of https://github.com/open-telemetry/opentelemetry-python-contrib/issues/4699?

**Comment by Atishyy27** [comment]
It is effectively a duplicate of #4699, and I think this one can be closed, because the crash is already gone on `main`.

The confusing part is that the line quoted in this issue looks untouched. `Match.PARTIAL` at `instrumentation/opentelemetry-instrumentation-fastapi/src/opentelemetry/instrumentation/fastapi/__init__.py:527` still calls `.path` with no guard, so grepping for the fix finds nothing. But #4700 (which fixed #4699) didn't guard that line. It added `_flatten_routes()`, which expands `_IncludedRouter` tree nodes into concrete routables *before* they reach the match loop. The type that lacked `.path` no longer gets there, so the unguarded access is unreachable.

I checked this by running the reproducer from this issue against `main` rather than reading the source, since the two disagree:

- With the pre-#4700 loop restored (`for starlette_route in app.routes`): `AttributeError: '_IncludedRouter' object has no attribute 'path'` at line 527, the exact traceback reported here.
- With current `main` (`_flatten_routes(app.routes)`): returns `405`, no crash.

Tested against fastapi 0.139.0 / starlette 1.3.1.

One thing that might be worth a follow-up regardless: because the fix works by filtering upstream rather than guarding the access, line 527 is still one unexpected route type away from the same `AttributeError`. A `getattr(starlette_route, "path", None)` check there would make it robust rather than merely unreachable. Happy to open a small PR for that if maintainers think it's worth it.

**Comment by ocelotl** [comment]
I asked Claude to review this issue and Claude suggests it be closed with this explanation:

> Duplicate of #4699, fixed by merged PR #4700; confirmed gone on main.
>
> Proof in `main`: [`fastapi/__init__.py#L473-L527`](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/94e851dfe333d47fdb52edb82635330668af284e/instrumentation/opentelemetry-instrumentation-fastapi/src/opentelemetry/instrumentation/fastapi/__init__.py#L473-L527)

To guard against a mistaken suggestion, Claude then independently re-verified this conclusion:

> Verified: this duplicates #4699 (fixed by merged PR #4700); the fix is present in current `fastapi/__init__.py`.

Claude evaluated this issue with high confidence that it can be closed.

Claude has classified this issue as a duplicate of another issue (#4699).

The intention of this comment is to make it easier for a human being to review this issue before making a decision.

**Comment by ocelotl** [comment]
@open-telemetry/python-maintainers please close this issue
