### ISSUE TITLE
Instrumentation not working with HTTPX 0.21.1 async client

### ISSUE THREAD

**Issue by jlugao** [open-telemetry/opentelemetry-python-contrib#818]
**Describe your environment** 

I am using python 3.9 and
```
   9   │ httpx==0.21.1
  11   │ opentelemetry-api==1.7.1
  12   │ opentelemetry-exporter-jaeger==1.7.1
  13   │ opentelemetry-exporter-jaeger-proto-grpc==1.7.1
  14   │ opentelemetry-exporter-jaeger-thrift==1.7.1
  15   │ opentelemetry-instrumentation==0.26b1
  16   │ opentelemetry-instrumentation-httpx==0.26b1
  17   │ opentelemetry-sdk==1.7.1
  18   │ opentelemetry-semantic-conventions==0.26b1
```

**Steps to reproduce**
clone https://github.com/jlugao/httpx-opentelemetry-bug
pip install requirements.txt
python sample.py

**What is the expected behavior?**
It should print 200 and send data to jaeger

**What is the actual behavior?**
```  File "/home/jlugao/.virtualenvs/example/lib/python3.9/site-packages/httpx/_client.py", line 1702, in _send_single_request
    response = await transport.handle_async_request(request)
TypeError: handle_async_request() missing 1 required positional argument: 'url' ```

**Additional context**
This is a small script that I did to reproduce an error happening in an app that is running on docker and fastapi.

**Comment by jlugao** [comment]
can anyone help me out with this? I'd be happy to create a PR for this if I have some guidance on what should I look for in the codebase

**Comment by ocelotl** [comment]
It seems like the [this call](https://github.com/encode/httpx/blob/0.21.1/httpx/_client.py#L1702) uses a single `request` argument while our instrumentation for httpx [expects `method` and `url`](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-httpx/src/opentelemetry/instrumentation/httpx/__init__.py#L266-L267) as arguments.

I ran your code in a virtual environment and modified httpx `_client.py` (around line 1702) file to this:
``` python
       with request_context(request=request):
            response = await transport.handle_async_request(
                request.method.encode("utf-8"), request.url
            )
```

After that, your code continues to run and fails later with another error. Maybe what is needed is a change in the httpx instrumentation to extract `method` and `url` from the `request` object?

**Comment by jianyuan** [comment]
I believe it's caused by this change: https://github.com/encode/httpx/pull/1840. The latest version of `httpx` that is compatible with this library is `0.19.0`.

**Comment by ruimartinsptl** [comment]
I think that it was solved here: https://github.com/open-telemetry/opentelemetry-python-contrib/pull/866

**Comment by ocelotl** [comment]
> I think that it was solved here: #866

@jlugao can you confirm, please?

**Comment by tuchandra** [comment]
FWIW I can't reproduce this with `opentelemetry-instrumentation-httpx = "^0.29b0"`.

**Comment by lzchen** [comment]
@jlugao 
Will be closing the issue for now. Feel free to open back up if you are still having issues.
